rm -f MartexCoind
rm -f obj/*.o
rm -f obj/*.P
rm -f obj/zerocoin/*.o
rm -f obj/zerocoin/*.P
rm -f obj-test/*.o
rm -f obj-test/*.P
rm -f obj/build.h
rm -f leveldb/libleveldb.a
rm -f leveldb/libmemenv.a
